<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\apicampeonatosfifa.aplicacion\apicampeonatosfifa.aplicacion.csproj" />
    <ProjectReference Include="..\apicampeonatosfifa.core\apicampeonatosfifa.core.csproj" />
    <ProjectReference Include="..\apicampeonatosfifa.dominio\apicampeonatosfifa.dominio.csproj" />
    <ProjectReference Include="..\apicampeonatosfifa.infreaestructura\apicampeonatosfifa.infraestructura.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

</Project>
